"""GPU health checks and R2 connectivity gates for cloud workers.

Unified from the shared patterns in Boltz-2 and OpenMM workers:
- GPU temperature + ECC error check via nvidia-smi
- Optional GPU VRAM minimum check
- R2 connectivity gate via upload script
"""

from __future__ import annotations

import logging
import subprocess
import sys
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger(__name__)


def check_gpu(*, min_memory_mib: int = 0, max_temp_c: int = 90) -> bool:
    """GPU health check — abort on critical hardware issues.

    Args:
        min_memory_mib: Minimum GPU VRAM in MiB (0 = skip check).
        max_temp_c: Maximum GPU temperature in Celsius.

    Returns:
        True if GPU is healthy, False if worker should abort.
    """
    try:
        # Query fields based on whether memory check is needed
        fields = "temperature.gpu,ecc.errors.uncorrected.aggregate.total"
        if min_memory_mib > 0:
            fields = "temperature.gpu,memory.total,ecc.errors.uncorrected.aggregate.total"

        result = subprocess.run(
            [
                "nvidia-smi",
                f"--query-gpu={fields}",
                "--format=csv,noheader,nounits",
            ],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
        parts = result.stdout.strip().split(",")

        if min_memory_mib > 0 and len(parts) >= 3:
            temp = int(parts[0].strip()) if parts[0].strip().isdigit() else 0
            mem = int(parts[1].strip()) if parts[1].strip().isdigit() else 0
            ecc = parts[2].strip()
        elif len(parts) >= 2:
            temp = int(parts[0].strip()) if parts[0].strip().isdigit() else 0
            mem = 0
            ecc = parts[1].strip()
        else:
            logger.warning("nvidia-smi returned unexpected output: %s", result.stdout)
            return True  # Proceed on parse failure

        if temp > max_temp_c:
            logger.error("ABORT: GPU temp %dC > %dC limit", temp, max_temp_c)
            return False

        if min_memory_mib > 0 and mem < min_memory_mib:
            logger.error(
                "ABORT: GPU memory %d MiB < %d MiB minimum", mem, min_memory_mib
            )
            return False

        if ecc not in ("0", "N/A", "[N/A]", ""):
            try:
                if int(ecc) > 0:
                    logger.error("ABORT: GPU ECC errors: %s", ecc)
                    return False
            except ValueError:
                pass

        if min_memory_mib > 0:
            logger.info("GPU OK: temp=%dC mem=%d MiB ecc=%s", temp, mem, ecc)
        else:
            logger.info("GPU OK: temp=%dC ecc=%s", temp, ecc)
        return True

    except Exception as exc:
        logger.warning("GPU check failed (proceeding): %s", exc)
        return True


def check_r2_connectivity(workspace: Path) -> bool:
    """Check R2 connectivity via the upload script.

    The upload script (``r2_upload.py``) is generated by the orchestrator
    and deployed to the workspace. Its ``--check`` mode does a lightweight
    R2 list operation.

    Args:
        workspace: Worker workspace directory.

    Returns:
        True if R2 is reachable or no upload script exists, False if
        connectivity check failed.
    """
    r2_script = workspace / "r2_upload.py"
    if not r2_script.exists():
        logger.info("No R2 upload script — skipping connectivity gate")
        return True

    try:
        result = subprocess.run(
            [sys.executable, str(r2_script), "--check"],
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        if result.returncode == 0:
            logger.info("R2 connectivity: OK")
            return True
        logger.error("R2 connectivity check FAILED: %s", result.stderr[:200])
        return False
    except subprocess.TimeoutExpired:
        logger.error("R2 connectivity check timed out")
        return False
    except Exception as exc:
        logger.error("R2 connectivity check error: %s", exc)
        return False
