"""GPU health checks and R2 connectivity gates for cloud workers.

- GPU temperature + ECC error check via nvidia-smi
- Optional GPU VRAM minimum check
- R2 connectivity gate via upload script
"""

from __future__ import annotations

import logging
import subprocess
import sys
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger(__name__)


def check_gpu(*, min_memory_mib: int = 0, max_temp_c: int = 90) -> bool:
    """GPU health check — abort on critical hardware issues.

    Args:
        min_memory_mib: Minimum GPU VRAM in MiB (0 = skip check).
        max_temp_c: Maximum GPU temperature in Celsius.

    Returns:
        True if GPU is healthy, False if worker should abort.
    """
    try:
        parts = _query_nvidia_smi(min_memory_mib)
    except Exception as exc:
        logger.warning("GPU check failed (proceeding): %s", exc)
        return True

    parsed = _parse_gpu_fields(parts, min_memory_mib)
    if parsed is None:
        return True  # Proceed on parse failure
    temp, mem, ecc = parsed

    if not _gpu_within_limits(temp, mem, ecc, min_memory_mib, max_temp_c):
        return False

    if min_memory_mib > 0:
        logger.info("GPU OK: temp=%dC mem=%d MiB ecc=%s", temp, mem, ecc)
    else:
        logger.info("GPU OK: temp=%dC ecc=%s", temp, ecc)
    return True


def _query_nvidia_smi(min_memory_mib: int) -> list[str]:
    """Run nvidia-smi once and return the comma-split query fields."""
    fields = "temperature.gpu,ecc.errors.uncorrected.aggregate.total"
    if min_memory_mib > 0:
        fields = "temperature.gpu,memory.total,ecc.errors.uncorrected.aggregate.total"
    result = subprocess.run(
        ["nvidia-smi", f"--query-gpu={fields}", "--format=csv,noheader,nounits"],
        capture_output=True,
        text=True,
        timeout=10,
        check=False,
    )
    return result.stdout.strip().split(",")


def _parse_gpu_fields(
    parts: list[str],
    min_memory_mib: int,
) -> tuple[int, int, str] | None:
    """Parse nvidia-smi output. Returns (temp_c, mem_mib, ecc) or None on shape mismatch."""
    if min_memory_mib > 0 and len(parts) >= 3:
        return _safe_int(parts[0]), _safe_int(parts[1]), parts[2].strip()
    if len(parts) >= 2:
        return _safe_int(parts[0]), 0, parts[1].strip()
    logger.warning("nvidia-smi returned unexpected output: %s", ",".join(parts))
    return None


def _safe_int(raw: str) -> int:
    """Parse an integer field from nvidia-smi output, defaulting to 0."""
    stripped = raw.strip()
    return int(stripped) if stripped.isdigit() else 0


def _gpu_within_limits(
    temp: int,
    mem: int,
    ecc: str,
    min_memory_mib: int,
    max_temp_c: int,
) -> bool:
    """Return True if all GPU health limits pass; log and return False on first breach."""
    if temp > max_temp_c:
        logger.error("ABORT: GPU temp %dC > %dC limit", temp, max_temp_c)
        return False
    if min_memory_mib > 0 and mem < min_memory_mib:
        logger.error("ABORT: GPU memory %d MiB < %d MiB minimum", mem, min_memory_mib)
        return False
    if _ecc_error_count(ecc) > 0:
        logger.error("ABORT: GPU ECC errors: %s", ecc)
        return False
    return True


def _ecc_error_count(ecc: str) -> int:
    """Parse ECC error count. Unknown/NA values return 0 (treat as healthy)."""
    if ecc in ("0", "N/A", "[N/A]", ""):
        return 0
    try:
        return int(ecc)
    except ValueError:
        return 0


def check_r2_connectivity(workspace: Path) -> bool:
    """Check R2 connectivity via the upload script.

    The upload script (``r2_upload.py``) is generated by the orchestrator
    and deployed to the workspace. Its ``--check`` mode does a lightweight
    R2 list operation.

    Args:
        workspace: Worker workspace directory.

    Returns:
        True if R2 is reachable or no upload script exists, False if
        connectivity check failed.
    """
    r2_script = workspace / "r2_upload.py"
    if not r2_script.exists():
        logger.info("No R2 upload script — skipping connectivity gate")
        return True

    try:
        result = subprocess.run(
            [sys.executable, str(r2_script), "--check"],
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        if result.returncode == 0:
            logger.info("R2 connectivity: OK")
            return True
        logger.error("R2 connectivity check FAILED: %s", result.stderr[:200])
        return False
    except subprocess.TimeoutExpired:
        logger.error("R2 connectivity check timed out")
        return False
    except Exception as exc:
        logger.error("R2 connectivity check error: %s", exc)
        return False
